#!/bin/bash
#MISE description="Generate objects (DeepCopy...)"

set -e

die() {
  echo "$1"
  exit 1
}

E2E_CMD_CONTROLLER_GEN="$(which controller-gen || exit 0)"
test -z "$E2E_CMD_CONTROLLER_GEN" && die "controller-gen not detected"

$E2E_CMD_CONTROLLER_GEN object paths="./..."